apiVersion: v1
kind: ConfigMap
metadata:
  name: resx-config
  namespace: resx
data:
  JWT_ISSUER: "ResX.Identity"
  JWT_AUDIENCE: "ResX"
  JWT_EXPIRY_MINUTES: "60"
  JWT_REFRESH_DAYS: "30"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_VHOST: "resx"
  RABBITMQ_USER: "guest"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"

  S3_SERVICE_URL: "https://storage.yandexcloud.net"
  S3_REGION: "ru-central1"
  S3_BUCKET: "resx-files"

  ASPNETCORE_ENVIRONMENT: "Production"
